
name: ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: install
        run: yarn install
        working-directory: ./app

      - name: build
        env: 
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
          GATSBY_API_GATEWAY_ENDPOINT_URL: ${{secrets.GATSBY_API_GATEWAY_ENDPOINT_URL}}
          GATSBY_403_REDIRECT_URL: ${{ secrets.GATSBY_403_REDIRECT_URL }}
          GATSBY_RECAPTCHA_SITE_KEY_VISIBLE: ${{secrets.GATSBY_RECAPTCHA_SITE_KEY_VISIBLE}}
          GATSBY_RECAPTCHA_SECRET_KEY_VISIBLE: ${{secrets.GATSBY_RECAPTCHA_SECRET_KEY_VISIBLE}}
        run: yarn build
        working-directory: ./app

      - name: Upload files
        env: 
          S3_CONTENTS_BUCKET: ${{ secrets.S3_CONTENTS_BUCKET }}
        run: |
          aws s3 sync ./public s3://$S3_CONTENTS_BUCKET/ --quiet
        working-directory: ./app